version: 2
updates:
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/pg"
    versions:
    - 7.14.10
    - 7.14.9
  - dependency-name: "@types/cors"
    versions:
    - 2.8.9
  - dependency-name: pg
    versions:
    - 8.5.1
